### PR TITLE
Allow TH generation of data types with infix constructors

### PR DESCRIPTION
**Pull request by RyanGlScott**
Currently, the Template Haskell mechanism for deriving `Generic` doesn't work correctly for data types with infix constructors. For example, if you have this:

```haskell
data Infix a b = a :?: b
$(deriveAll ''Infix)
```

Then `deriveAll` would attempt to define `data Infix_:?:_`, which Template Haskell rejects.

To get around this, I use a trick from [`genifunctors`](https://github.com/danr/genifunctors/blob/4677bb57423b1b380ce9b50cc3d765a5c49a957a/Data/Generics/Genifunctors.hs#L272-278) and sanitize each `nameBase` before being used in a type name. Non-alphanumeric characters are replaced by their ASCII codes, so the above example would generate `data NInfix_N_58_63_58_` instead.

Since this changes the names of generated identifiers, I had to make some changes to `Examples.hs` to make it work again.

### CODE REVIEW

**Comment by dreixel** [comment]
What are the changes regarding transformM?

**Comment by RyanGlScott** [comment]
Oh, that. I didn't make any changes to the Uniplate-related code. The [original usage](https://github.com/dreixel/generic-deriving/blob/bb6fa2a31481cf5935a8ff1c388959fdeeb25755/examples/Examples.hs#L98-104) of `transformdefault` in the `Example.hs` file was this:

```haskell
instance Uniplate Tree where
    ...
    transform = transformdefault
    transformM = transformdefault
```

but `transformM = transformdefault` gives a compilation error:

```
    Couldn't match expected type `m Tree' with actual type `Tree'
    Expected type: (Tree -> m Tree) -> Tree -> m Tree
      Actual type: (Tree -> Tree) -> Tree -> Tree
    In the expression: transformdefault
    In an equation for `transformM': transformM = transformdefault
```

I presumed this was a typo and changed `transformM = transformdefault` to `transformM = transformMdefault`, which seemed to make the examples work on GHC 7.0 (I could be wrong though).
